CREATE TABLE FOODTRIANGLEREQS
(
ID INTEGER NOT NULL,
SEX CHAR(6) NOT NULL,
MINAGE INTEGER NOT NULL,
MAXAGE INTEGER NOT NULL, 
FRUITSREQ INTEGER NOT NULL,
VEGETABLESREQ INTEGER NOT NULL,
GRAINSREQ INTEGER NOT NULL,
PROTEINREQ INTEGER NOT NULL,
DAIRYREQ INTEGER NOT NULL,
OILSREQ INTEGER NOT NULL,
PRIMARY KEY (ID)
);

INSERT INTO FOODTRIANGLEREQS VALUES (0, 'MALE', 2, 3, 1, 1, 3, 2, 2, 3);
INSERT INTO FOODTRIANGLEREQS VALUES (1, 'FEMALE', 2, 3, 1, 1, 3, 2, 2, 3);
INSERT INTO FOODTRIANGLEREQS VALUES (2, 'MALE', 4, 8, 1.5, 1.5, 5, 4, 2.5, 4);
INSERT INTO FOODTRIANGLEREQS VALUES (3, 'FEMALE', 4, 8, 1.5, 1.5, 5, 4, 2.5, 4);
INSERT INTO FOODTRIANGLEREQS VALUES (4, 'MALE', 9, 13, 1.5, 2.5, 6, 5, 3, 5);
INSERT INTO FOODTRIANGLEREQS VALUES (5, 'FEMALE', 9, 13, 1.5, 2, 5, 5, 3, 5);
INSERT INTO FOODTRIANGLEREQS VALUES (6, 'MALE', 14, 18, 2, 3, 8, 6.5, 3, 6);
INSERT INTO FOODTRIANGLEREQS VALUES (7, 'FEMALE', 14, 18, 1.5, 2.5, 6, 5, 3, 5);
INSERT INTO FOODTRIANGLEREQS VALUES (8, 'MALE', 19, 30, 2, 3, 8, 6.5, 3, 7);
INSERT INTO FOODTRIANGLEREQS VALUES (9, 'FEMALE', 19, 30, 2, 2.5, 6, 5.5, 3, 6); 
INSERT INTO FOODTRIANGLEREQS VALUES (10, 'MALE', 31, 50, 2, 3, 7, 6, 3, 6);
INSERT INTO FOODTRIANGLEREQS VALUES (11, 'FEMALE', 31, 50, 1.5, 2.5, 6, 5, 3, 5);
INSERT INTO FOODTRIANGLEREQS VALUES (12, 'MALE', 51, 150, 2, 2.5, 6, 5.5, 3, 6);
INSERT INTO FOODTRIANGLEREQS VALUES (13, 'FEMALE', 51, 150, 1.5, 2, 5, 5, 3, 5);

CREATE TABLE FOODTRIANGLEUSER
(
ID INTEGER NOT NULL,
FIRSTNAME VARCHAR(255) NOT NULL,
LASTNAME VARCHAR(255) NOT NULL,
SEX CHAR(6) NOT NULL,
BIRTHDATE VARCHAR(255) NOT NULL,
AGE INTEGER NOT NULL,
USERNAME VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE FOODTRIANGLEDAY
(
ID INTEGER NOT NULL,
DAY VARCHAR(255) NOT NULL,
FRUITSAMOUNT INTEGER NOT NULL,
VEGETABLESAMOUNT INTEGER NOT NULL,
GRAINSAMOUNT INTEGER NOT NULL,
PROTEINAMOUNT INTEGER NOT NULL,
DAIRYAMOUNT INTEGER NOT NULL,
OILSAMOUNT INTEGER NOT NULL,
USERID INTEGER NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (USERID) REFERENCES FOODTRIANGLEUSER(ID)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
);
